name: quickly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+3
  lottie: ^3.1.2
  get: ^4.6.5
  http: ^1.2.1

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  iconsax_flutter: ^1.0.0
  connectivity_plus: ^5.0.1
  get_storage: ^2.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf

      
