// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn9yhKnKVYdtzrEAAUZTlYzJowmxUJUos',
    appId: '1:680650941284:web:11d5fc8b95f641a0045071',
    messagingSenderId: '680650941284',
    projectId: 'quicklyapp-61eaf',
    authDomain: 'quicklyapp-61eaf.firebaseapp.com',
    storageBucket: 'quicklyapp-61eaf.appspot.com',
    measurementId: 'G-P2HH863QZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWecAsIzR5sK-btP4KiOHFsOR1ismfnco',
    appId: '1:680650941284:android:b1ecdcc132f7c441045071',
    messagingSenderId: '680650941284',
    projectId: 'quicklyapp-61eaf',
    storageBucket: 'quicklyapp-61eaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1VerufSd1NOv97bLasuymnEQlu80Lzo',
    appId: '1:680650941284:ios:ac4e003cb1beb217045071',
    messagingSenderId: '680650941284',
    projectId: 'quicklyapp-61eaf',
    storageBucket: 'quicklyapp-61eaf.appspot.com',
    androidClientId: '680650941284-cgb2k3oh6a4va3na476djj41j9b42bbp.apps.googleusercontent.com',
    iosClientId: '680650941284-fmsn3gr9rdt0fmb570es73kc5gir8780.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1VerufSd1NOv97bLasuymnEQlu80Lzo',
    appId: '1:680650941284:ios:ac4e003cb1beb217045071',
    messagingSenderId: '680650941284',
    projectId: 'quicklyapp-61eaf',
    storageBucket: 'quicklyapp-61eaf.appspot.com',
    androidClientId: '680650941284-cgb2k3oh6a4va3na476djj41j9b42bbp.apps.googleusercontent.com',
    iosClientId: '680650941284-fmsn3gr9rdt0fmb570es73kc5gir8780.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn9yhKnKVYdtzrEAAUZTlYzJowmxUJUos',
    appId: '1:680650941284:web:19f227b74f874197045071',
    messagingSenderId: '680650941284',
    projectId: 'quicklyapp-61eaf',
    authDomain: 'quicklyapp-61eaf.firebaseapp.com',
    storageBucket: 'quicklyapp-61eaf.appspot.com',
    measurementId: 'G-EK2C7109MH',
  );
}
